from enum import Enum

class MessageOwner(Enum):
    """
    Enum to identify the message owner/sender.
    
    Defines who sent the message in the conversation context:
    - USER: Message sent by user/client
    - AGENT: Message sent by human agent
    - SYSTEM: Automatic system message
    - TOOL: Message generated by tools/automation
    - SUPPORT: Message sent by support
    """
    USER = "user"
    AGENT = "agent"
    SYSTEM = "system"
    TOOL = "tool"
    SUPPORT = "support"

    def __repr__(self) -> str:
        return f"MessageOwner.{self.name}"
