"""
Enums module for the Owner project.
Contains all enumeration types used across the application.
"""
from enum import Enum


class ConversationStatus(Enum):
    """
    Enum for conversation status.
    
    Defines the state of the conversation lifecycle:
    - PENDING: Active conversation, awaiting interaction
    - PROGRESS: Conversation in progress
    - AGENT_CLOSED: Conversation closed by agent
    - SUPPORT_CLOSED: Conversation closed by support team
    - USER_CLOSED: Conversation closed by user
    - EXPIRED: Conversation automatically expired by system
    - FAILED: Conversation closed due to system failure
    - IDLE_TIMEOUT: Conversation paused due to inactivity timeout
    """
    PENDING = "pending"
    PROGRESS = "progress"
    AGENT_CLOSED = "agent_closed"
    SUPPORT_CLOSED = "support_closed"
    USER_CLOSED = "user_closed"
    EXPIRED = "expired"
    FAILED = "failed"
    IDLE_TIMEOUT = "idle_timeout"
    
    @classmethod
    def active_statuses(cls):
        """Returns statuses considered as active."""
        return [cls.PENDING, cls.PROGRESS]
    
    @classmethod
    def closed_statuses(cls):
        """Returns statuses considered as closed."""
        return [
            cls.AGENT_CLOSED,
            cls.SUPPORT_CLOSED,
            cls.USER_CLOSED,
            cls.EXPIRED,
            cls.FAILED,
            cls.IDLE_TIMEOUT
        ]

    def __repr__(self) -> str:
        return f"ConversationStatus.{self.name}"


class MessageOwner(Enum):
    """
    Enum to identify the message owner/sender.
    
    Defines who sent the message in the conversation context:
    - USER: Message sent by user/client
    - AGENT: Message sent by human agent
    - SYSTEM: Automatic system message
    - TOOL: Message generated by tools/automation
    - SUPPORT: Message sent by support
    """
    USER = "user"
    AGENT = "agent"
    SYSTEM = "system"
    TOOL = "tool"
    SUPPORT = "support"

    def __repr__(self) -> str:
        return f"MessageOwner.{self.name}"


class MessageType(Enum):
    """
    Enum to classify message content type.
    
    Defines the format and type of message content:
    - TEXT: Simple text message
    - IMAGE: Message containing image
    - AUDIO: Audio/voice message
    - VIDEO: Video message
    - DOCUMENT: Document message
    """
    TEXT = "text"
    IMAGE = "image"
    AUDIO = "audio"
    VIDEO = "video"
    DOCUMENT = "document"

    def __repr__(self) -> str:
        return f"MessageType.{self.name}"


class MessageDirection(Enum):
    """
    Enum for message direction.
    
    Defines the direction of message flow:
    - INBOUND: Message received by the system
    - OUTBOUND: Message sent to the client
    """
    INBOUND = "inbound"
    OUTBOUND = "outbound"

    def __repr__(self) -> str:
        return f"MessageDirection.{self.name}"


class UserRole(Enum):
    """
    Enum for user roles.
    
    Defines the role of users in the system:
    - ADMIN: Administrator with full access
    - AGENT: Agent with limited access
    - USER: Regular user
    """
    ADMIN = "admin"
    AGENT = "agent"
    USER = "user"

    def __repr__(self) -> str:
        return f"UserRole.{self.name}"
